description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: "18"
    - name: Configure git to use HTTPS instead of SSH
      run: 'git config --global url."https://github.com/".insteadOf "git@github.com:"'
      shell: bash
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
